
-- Revenue Analysis: Top X%, Revenue Contribution

-- 1. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine
SELECT cuisine, SUM(rating_count*cost) AS revenue
FROM(SELECT * ,
	 cost*rating_count as revenue,
	 ROW_NUMBER() OVER(PARTITION BY cuisine ORDER BY cost*rating_count DESC) AS rank FROM restaurants) t 
WHERE t.rank < 6
GROUP BY cuisine
ORDER BY REVENUE DESC;


-- 2. What is the total revenue generated by top 1% restaurants
SELECT SUM(rating_count*cost) AS revenue
FROM(SELECT * ,
	 cost*rating_count as revenue,
	 ROW_NUMBER() OVER(ORDER BY cost*rating_count DESC) AS rank FROM restaurants) t 
WHERE t.rank <= 614;


-- 3. Total revenue by top 20% restaurants
SELECT SUM(rating_count*cost) AS revenue
FROM(SELECT * ,
	 cost*rating_count as revenue,
	 ROW_NUMBER() OVER(ORDER BY cost*rating_count DESC) AS rank FROM restaurants) t 
WHERE t.rank <= 12285;


-- 4. What % of revenue is generated by top 20% of restaurants with respect to total revenue?
WITH Q1 AS (SELECT SUM(rating_count*cost) AS top_revenue
            FROM(SELECT *,
				 rating_count*cost,
                 ROW_NUMBER() OVER(ORDER BY rating_count*cost DESC) AS rank FROM restaurants) t
            WHERE t.rank <= 6017),    
     Q2 AS (SELECT SUM(rating_count*cost) AS total_revenue FROM restaurants)
     
SELECT (top_revenue/total_revenue)*100 AS revenue% FROM Q1,Q2;  